
export default({
    /* Bloodlines */
    SEND_PAGED: 'SEND_PAGED',
    HANDLE_PAGED: 'HANDLE_PAGED',
    TRIGGERS: 'TRIGGERS',
    CONTENTS: 'CONTENTS',
    RECEIPTS: 'RECEIPTS',
    REQUEST: 'REQUEST',
    HANDLE: 'HANDLE',
    ERROR: 'ERROR',
    ERROR_RESOLVE: 'ERROR_RESOLVE',
    TIMEOUT: 'TIMEOUT',

    /* Coinage */
    REQUEST_UPDATE_CUSTOMER_PAYMENT_INFO: 'REQUEST_UPDATE_CUSTOMER_PAYMENT_INFO',
    RECEIVE_UPDATED_CUSTOMER_PAYMENT_INFO: 'RECEIVE_UPDATED_CUSTOMER_PAYMENT_INFO',
    ERROR_UPDATING_CUSTOMER_PAYMENT_INFO: 'ERROR_UPDATING_CUSTOMER_PAYMENT_INFO',
    REQUEST_CREATE_CUSTOMER_PAYMENT_INFO: 'REQUEST_CREATE_CUSTOMER_PAYMENT_INFO',
    RECEIVE_CREATED_CUSTOMER_PAYMENT_INFO: 'RECEIVE_CREATED_CUSTOMER_PAYMENT_INFO',
    ERROR_CREATING_CUSTOMER_PAYMENT_INFO: 'ERROR_CREATING_CUSTOMER_PAYMENT_INFO',
    COINAGE_SUBSCRIBE: 'COINAGE_SUBSCRIBE',

    /* Roaster */
    ROASTER: 'ROASTER',
    RECEIVE_ROASTER: 'RECEIVE_ROASTER',
    ERROR_ROASTER: 'ERROR_ROASTER',

    /* User */
    LOGOUT: 'LOGOUT',
    RECEIVE_USER: 'RECEIVE_USER',
    ERROR_USER: 'ERROR_USER',

    /* Covenant */
    COVENANT_SUBSCRIPTIONS: 'COVENANT_SUBSCRIPTIONS',

    /* Warehouse */
    WAREHOUSE_ITEM: 'WAREHOUSE_ITEM',
    WAREHOUSE_ITEMS: 'WAREHOUSE_ITEMS'
});
