
export default({
    /* Bloodlines */
    HANDLE_PAGED: 'HANDLE_PAGED',
    ERROR_PAGED: 'ERROR_PAGED',
    TRIGGERS: 'TRIGGERS',
    CONTENTS: 'CONTENTS',
    RECEIPTS: 'RECEIPTS',
    REQUEST: 'REQUEST',
    HANDLE: 'HANDLE',
    ERROR: 'ERROR',
    TIMEOUT: 'TIMEOUT',

    /* Coinage */
    REQUEST_UPDATE_CUSTOMER_PAYMENT_INFO: 'REQUEST_UPDATE_CUSTOMER_PAYMENT_INFO',
    RECEIVE_UPDATED_CUSTOMER_PAYMENT_INFO: 'RECEIVE_UPDATED_CUSTOMER_PAYMENT_INFO',
    ERROR_UPDATING_CUSTOMER_PAYMENT_INFO: 'ERROR_UPDATING_CUSTOMER_PAYMENT_INFO',
    REQUEST_CREATE_CUSTOMER_PAYMENT_INFO: 'REQUEST_CREATE_CUSTOMER_PAYMENT_INFO',
    RECEIVE_CREATED_CUSTOMER_PAYMENT_INFO: 'RECEIVE_CREATED_CUSTOMER_PAYMENT_INFO',
    ERROR_CREATING_CUSTOMER_PAYMENT_INFO: 'ERROR_CREATING_CUSTOMER_PAYMENT_INFO',

    /* Roaster */
    REQUEST_CREATE_ROASTER: 'REQUEST_CREATE_ROASTER',
    RECEIVE_CREATED_ROASTER: 'RECEIVE_CREATIED_ROASTER',
    ERROR_CREATING_ROASTER: 'ERROR_CREATING_ROASTER',

    /* User */
    LOGOUT: 'LOGOUT',
    RECEIVE_USER: 'RECEIVE_USER',
    ERROR_USER: 'ERROR_USER',

    /* Warehouse */
    WAREHOUSE_ITEMS: 'WAREHOUSE_ITEMS'
});
